"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { Brain, UserCheck } from "lucide-react";
import { cn } from "@/lib/utils";

const SUBJECTIVE_FIELDS: { key: string; label: string; hint: string }[] = [
  { key: "founderReliability", label: "Founder reliability", hint: "Trust, execution history, commitments kept" },
  { key: "teamCredibility", label: "Team credibility", hint: "Composition, domain fit, complementarity" },
  { key: "marketAttractiveness", label: "Market attractiveness", hint: "TAM, growth, competitive intensity" },
  { key: "potentialRoi", label: "Potential ROI", hint: "Outlier potential vs. portfolio model" },
  { key: "strategicPositioning", label: "Strategic positioning", hint: "Moat, differentiation, defensibility" },
  { key: "investorConfidence", label: "Investor confidence", hint: "Gut-check after founder conversation" },
  { key: "productVisionQuality", label: "Product vision quality", hint: "Clarity, ambition, articulation" },
];

export function AnalystNotes() {
  const [values, setValues] = useState<Record<string, number>>({});
  const [freeText, setFreeText] = useState("");

  return (
    <div className="rounded-2xl border border-bone-300/20 bg-bone-50/[0.02] overflow-hidden">
      {/* Header — visually distinct from ML cards (warm tone, not signal cyan) */}
      <div className="px-6 py-5 bg-bone-50/[0.03] border-b border-bone-300/15">
        <div className="flex items-start justify-between gap-4">
          <div className="flex items-start gap-3">
            <div className="h-9 w-9 rounded-full bg-bone-300/10 border border-bone-300/20 flex items-center justify-center shrink-0">
              <UserCheck className="h-4 w-4 text-bone-200" />
            </div>
            <div>
              <h3 className="font-display text-xl text-bone-50">Analyst notes</h3>
              <p className="text-xs text-[var(--text-secondary)] mt-1">
                Subjective human evaluation — visible to the analyst team only.
              </p>
            </div>
          </div>
          <span className="hidden sm:inline-flex shrink-0 items-center gap-2 px-3 py-1.5 rounded-full bg-bone-300/[0.06] border border-bone-300/20 font-mono text-[0.6rem] uppercase tracking-[0.18em] text-bone-200">
            Not generated by the model
          </span>
        </div>

        <div className="mt-4 rounded-lg bg-ink-900/60 border border-bone-300/10 px-4 py-3 flex items-start gap-3">
          <Brain className="h-3.5 w-3.5 text-[var(--text-muted)] mt-0.5 shrink-0" />
          <p className="text-[0.72rem] leading-relaxed text-[var(--text-secondary)]">
            <span className="text-bone-50">These analyst notes are NOT generated by the machine learning model</span> and represent subjective human evaluation. They are stored alongside, but never used as input to, the prediction pipeline.
          </p>
        </div>
      </div>

      {/* Subjective rating fields */}
      <div className="p-6 space-y-4">
        {SUBJECTIVE_FIELDS.map((field) => (
          <div key={field.key} className="grid grid-cols-12 gap-4 items-center">
            <div className="col-span-12 sm:col-span-4">
              <p className="text-sm text-bone-50">{field.label}</p>
              <p className="text-[0.65rem] text-[var(--text-muted)] mt-0.5">{field.hint}</p>
            </div>
            <div className="col-span-10 sm:col-span-7">
              <div className="flex items-center gap-1.5">
                {[1, 2, 3, 4, 5].map((v) => (
                  <button
                    key={v}
                    onClick={() =>
                      setValues((cur) => ({
                        ...cur,
                        [field.key]: cur[field.key] === v ? 0 : v,
                      }))
                    }
                    className={cn(
                      "h-7 w-7 rounded-md font-mono text-xs transition-all",
                      (values[field.key] ?? 0) >= v
                        ? "bg-bone-200 text-ink-950"
                        : "bg-ink-800/60 text-[var(--text-muted)] hover:bg-ink-700"
                    )}
                  >
                    {v}
                  </button>
                ))}
              </div>
            </div>
            <div className="col-span-2 sm:col-span-1 text-right">
              <span className="font-mono text-xs text-[var(--text-muted)] tabular-nums">
                {values[field.key] ? `${values[field.key]}/5` : "—"}
              </span>
            </div>
          </div>
        ))}

        {/* Free text */}
        <div className="pt-4 border-t border-bone-300/10">
          <label className="block">
            <p className="text-sm text-bone-50 mb-2">Founder meeting notes</p>
            <textarea
              value={freeText}
              onChange={(e) => setFreeText(e.target.value)}
              rows={4}
              placeholder="Conviction, red flags, follow-up actions — your unfiltered take. Not parsed by the model."
              className="w-full rounded-lg bg-ink-900/60 border border-bone-300/10 px-3 py-2 text-sm placeholder:text-[var(--text-muted)] focus:outline-none focus:border-bone-300/30 transition-colors resize-none"
            />
          </label>
        </div>

        <div className="flex items-center justify-between pt-2">
          <p className="font-mono text-[0.6rem] uppercase tracking-[0.18em] text-[var(--text-muted)]">
            Auto-saved · {new Date().toLocaleString("en-GB", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" })}
          </p>
          <span className="font-mono text-[0.6rem] uppercase tracking-[0.18em] text-bone-300/60">
            HUMAN · IN · THE · LOOP
          </span>
        </div>
      </div>
    </div>
  );
}
